//
//  BF_RedX.h
//  X-On-Button
//
//  Created by Thomas Strauß on 08.09.16.
//  Copyright (c) 2016 BeanFactory. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface BF_RedX : NSObject

// Drawing Methods
+ (void)drawRedxWithFrame: (CGRect)frame;

@end
